# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-13 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('docfile', models.FileField(blank=True, upload_to='')),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('price_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('date_of_purchase', models.DateField(blank=True, null=True)),
                ('date_of_sale', models.DateField(blank=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=255)),
                ('year', models.DateField(blank=True, null=True)),
                ('cover', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comics', to='comic.User'),
        ),
        migrations.AddField(
            model_name='comic',
            name='my_collection',
            field=models.ManyToManyField(related_name='added_to_my_collect_comic', to='comic.User'),
        ),
        migrations.AddField(
            model_name='comic',
            name='sold',
            field=models.ManyToManyField(related_name='added_to_sold_comic', to='comic.User'),
        ),
        migrations.AddField(
            model_name='comic',
            name='wishlist',
            field=models.ManyToManyField(related_name='added_to_wishlist_comic', to='comic.User'),
        ),
    ]
