# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-13 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='date_of_sale',
            field=models.DateField(blank=True, null=True),
        ),
    ]
