# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-27 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_auto_20190313_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='docfile',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
